services:
  - type: web
    name: asala-hub-backend
    env: docker
    context: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: AUTO_SEED
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
