"""add_course_version_and_is_deleted

Revision ID: 467567e12720
Revises: d2e83f45678b
Create Date: 2026-07-27 13:34:33.106482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '467567e12720'
down_revision: Union[str, None] = 'd2e83f45678b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('course', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_course_is_deleted'), 'course', ['is_deleted'], unique=False)
    op.create_index('idx_module_course_order', 'module', ['course_id', 'order_index'], unique=False)
    op.add_column('submission', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('submission', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index('idx_submission_assignment_student', 'submission', ['assignment_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_submission_is_deleted'), 'submission', ['is_deleted'], unique=False)
    op.create_index('idx_tx_log_user_synced_time', 'transactionlog', ['user_id', 'synced_at', 'client_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tx_log_user_synced_time', table_name='transactionlog')
    op.drop_index(op.f('ix_submission_is_deleted'), table_name='submission')
    op.drop_index('idx_submission_assignment_student', table_name='submission')
    op.drop_column('submission', 'is_deleted')
    op.drop_column('submission', 'version')
    op.drop_index('idx_module_course_order', table_name='module')
    op.drop_index(op.f('ix_course_is_deleted'), table_name='course')
    op.drop_column('course', 'is_deleted')
    op.drop_column('course', 'version')
    # ### end Alembic commands ###
