"""add_indexes_and_optimize

Revision ID: b2b899c8275e
Revises: 16da51baf570
Create Date: 2026-07-17 10:21:11.912045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2b899c8275e'
down_revision: Union[str, None] = '16da51baf570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assignment_course_id'), 'assignment', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_educator_id'), 'course', ['educator_id'], unique=False)
    op.create_index(op.f('ix_module_course_id'), 'module', ['course_id'], unique=False)
    op.create_index(op.f('ix_submission_assignment_id'), 'submission', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submission_student_id'), 'submission', ['student_id'], unique=False)
    op.create_index(op.f('ix_submission_sync_status'), 'submission', ['sync_status'], unique=False)
    op.create_index(op.f('ix_transactionlog_client_timestamp'), 'transactionlog', ['client_timestamp'], unique=False)
    op.create_index(op.f('ix_transactionlog_synced_at'), 'transactionlog', ['synced_at'], unique=False)
    op.create_index(op.f('ix_transactionlog_user_id'), 'transactionlog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactionlog_user_id'), table_name='transactionlog')
    op.drop_index(op.f('ix_transactionlog_synced_at'), table_name='transactionlog')
    op.drop_index(op.f('ix_transactionlog_client_timestamp'), table_name='transactionlog')
    op.drop_index(op.f('ix_submission_sync_status'), table_name='submission')
    op.drop_index(op.f('ix_submission_student_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_assignment_id'), table_name='submission')
    op.drop_index(op.f('ix_module_course_id'), table_name='module')
    op.drop_index(op.f('ix_course_educator_id'), table_name='course')
    op.drop_index(op.f('ix_assignment_course_id'), table_name='assignment')
    # ### end Alembic commands ###
