export const COPY = {
  en: {
    brand: "Asala Hub",
    role: "Institutional Student",
    course: "Foundations of Public Health",
    courseCode: "PUBH-110",
    modulesLabel: "Modules",
    cached: "Cached · available offline",
    notCached: "Not cached yet",
    open: "Open",
    m1: "Course Overview & Syllabus",
    m2: "Epidemiology Basics",
    m3: "Case Study: Health Access in Displacement Settings",
    assignment: "Assignment",
    assignmentTitle: "Reflection: Health Access in Displacement Settings",
    due: "Due",
    dueDate: "Fri, Jul 24",
    reflectionLabel: "Your reflection",
    placeholder: "Start writing — your work is kept on this device until it can sync.",
    saveBtn: "Save",
    savedBtn: "Saved",
    savedNote: "Saved locally. Will sync when you reconnect.",
    savingLocal: "works offline",
    statusOnline: "All changes synced",
    statusOffline: "You're offline. Your work is saved and will sync when you reconnect.",
    statusSyncing: "Syncing your latest work…",
    lastSync: "Last synced",
    demoPanel: "Demo controls",
    demoConn: "Connection state",
    demoLang: "Language",
    minutesAgo: "12 min ago",
  },
  ar: {
    brand: "أصالة هَب",
    role: "طالب مؤسسي",
    course: "أسس الصحة العامة",
    courseCode: "PUBH-110",
    modulesLabel: "الوحدات",
    cached: "محفوظ · متاح دون اتصال",
    notCached: "غير محفوظ بعد",
    open: "فتح",
    m1: "نظرة عامة على المقرر والمنهج",
    m2: "أساسيات علم الأوبئة",
    m3: "دراسة حالة: الوصول إلى الرعاية الصحية في أماكن النزوح",
    assignment: "الواجب",
    assignmentTitle: "تأمل: الوصول إلى الرعاية الصحية في أماكن النزوح",
    due: "الموعد النهائي",
    dueDate: "الجمعة، ٢٤ يوليو",
    reflectionLabel: "تأملك",
    placeholder: "ابدأ الكتابة — يبقى عملك على هذا الجهاز حتى تتم مزامنته.",
    saveBtn: "حفظ",
    savedBtn: "تم الحفظ",
    savedNote: "تم الحفظ محليًا. ستتم المزامنة عند إعادة الاتصال.",
    savingLocal: "يعمل بدون اتصال",
    statusOnline: "تمت مزامنة كل التغييرات",
    statusOffline: "أنت غير متصل. تم حفظ عملك وستتم مزامنته عند إعادة الاتصال.",
    statusSyncing: "جارٍ مزامنة أحدث أعمالك…",
    lastSync: "آخر مزامنة",
    demoPanel: "أدوات العرض التجريبي",
    demoConn: "حالة الاتصال",
    demoLang: "اللغة",
    minutesAgo: "قبل ١٢ دقيقة",
  },
} as const;

export type Language = keyof typeof COPY;
